### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by 89z** [1lann/messenger#2]
If I use this code:

~~~go
package messenger
import "testing"

func TestLogin(t *testing.T) {
   err := NewSession().Login("srpen6@gmail.com", password)
   if err != nil {
      t.Fatal(err)
   }
}
~~~

I get an error

**Comment by 1lann** [comment]
This library is no longer maintained. Use the official Facebook APIs instead. See https://developers.facebook.com/docs/messenger-platform/getting-started/
